### PR TITLE
chore: callbacks -> async / await

### PR DESCRIPTION
**Pull request by dirkmc**
BREAKING CHANGE: All places in the API that used callbacks are now replaced with async/await

Depends on
- [x] https://github.com/multiformats/js-multihashing-async/pull/37
- [x] https://github.com/ipfs/js-ipfs-repo/pull/189

### CODE REVIEW

**Comment by vmx** [comment]
I can reproduce the test failures from Travis locally.

**Comment by dirkmc** [comment]
There are a couple of things that need to be fixed in the dependencies before the tests will pass - see eg https://github.com/ipfs/js-ipfs-repo/pull/189#discussion_r265324279

**Comment by vmx** [comment]
@dirkmc Please review my changes. If you're OK with them, I'll do a force push having a single commit only.

Thanks for the original PR! :)

**Comment by dirkmc** [comment]
LGTM 👍

Note: I can't approve the changes as I opened the PR :)

**Comment by vmx** [comment]
Just squashed the commit that was already reviewed. Hence merging.

**Pull request merged**
